---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-9484
    - profile-9484
    - user-9484
    - webserver-9484

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"
